### ISSUE TITLE
fix: export to superstructure

### ISSUE THREAD

**Issue by simb-sdu** [polca/premise#65] opened 2022-03-21 17:32 UTC
Got an error when exporting ecoinvent 3.8 cutoff to a superstructure database: rows exceed allowed max.

fix:

Anaconda3\envs\PREMISE\Lib\site-packages\pandas\io\formats\excel.py
line 472

increase the value for max rows

**Comment by romainsacchi** [comment] 2022-03-28 17:10
That is surprising.
May I know what type of transformation and which scenario you have used to create your superstructure database?

**Comment by simb-sdu** [comment] 2022-03-28 18:00
I was able to circumvent the issue by increasing the` max_columns` variable in `Anaconda3\envs\PREMISE\Lib\site-packages\pandas\io\formats\excel.py`

A few days later, i reinstalled the environment and the issue disappeared (without changeing `max_columns`). This surprises me, as I had already tried said solution before posting this issue

**Comment by simb-sdu** [comment] 2022-03-28 18:01
> That is surprising. May I know what type of transformation and which scenario you have used to create your superstructure database?

`{"model":"remind", "pathway":"SSP2-Base", "year":2020},`
`update_all()`

**Comment by simb-sdu** [comment] 2022-03-28 18:05
It seems the` update_all()` gives some errors, as i am able to load the superstructure file in AB, but get assertionerror: missing keys when i try to calculate results.

To test, i managed to create a functioning superstructure database which only transformed `update_steel()`. @marc-vdm was kind to try and help troubleshoot, and suggests the error is when exporting the brightway superstructre database. I hope it is alright i forward this email to you?

**Comment by romainsacchi** [comment] 2022-03-28 18:09
Could you make sure you pulled the latest version (1.0.6 or 1.0.7) and let me know if this issue persists?
I remember encountering this issue because of some outdated biosphere flows, which I then fixed a few days ago.

**Comment by simb-sdu** [comment] 2022-03-28 18:14
> Could you make sure you pulled the latest version (1.0.6 or 1.0.7) and let me know if this issue persists? I remember encountering this issue because of some outdated biosphere flows, which I then fixed a few days ago.

I tried updating to 1.0.6 (as well in a brand new environment) but this version gave errors with `NewDatabase()` hence I had to downgrade to 1.0.5. Will try with 1.0.7 once i get time, and report back

**Comment by romainsacchi** [comment] 2022-03-28 18:16
Sorry about this.
Could you paste here the error you got? That's also useful, to make sure it is not reproduced in ulterior versions.

**Comment by romainsacchi** [comment] 2022-03-30 12:35
Issue fixed with #69 . Update to v.1.0.8.

**Closed as completed by romainsacchi** 2022-03-30 12:35 UTC
